import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavigationBar from "./navigationBar";

import { Work_Sans } from "next/font/google";


const workSans = Work_Sans({
  subsets: ["latin"],
  variable: "--font-work-sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={workSans.className}>
        <NavigationBar />
        {children}
      </body>
    </html>
  );
}
